######################## default configuration ####################
baseURL = "/"
title = "Mikroways"
theme = "bizcraft-hugo"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
#disqusShortname = "#" # get your shortname form here : https://disqus.com
removePathAccents = true


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
#[[params.plugins.css]]
#link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"
[[params.plugins.css]]
link = "css/timeline.css"
[[params.override_css]]
link = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
link = "https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/style-switcher.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
[[params.plugins.js]]
link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"
[[params.plugins.js]]
link = "js/contactformlambda.js"
[[params.plugins.js]]
link = "js/newsletter.js"
[[params.plugins.js]]
link = "https://kit.fontawesome.com/4e9fd50276.js"


############################## English navigation ###############################

[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About us"
weight = 2
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "About Mikroways"
  URL = "about"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "The team"
  URL = "team"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "Our customers"
  URL = "clients"
  weight = 3

[[Languages.en.menu.main]]
name = "Success stories"
URL = "portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

############################## Spanish navigation ###############################

[[Languages.es.menu.main]]
name = "Inicio"
URL = "/es"
weight = 1

[[Languages.es.menu.main]]
name = "La empresa"
weight = 2
hasChildren = true

  [[Languages.es.menu.main]]
  parent = "La empresa"
  name = "Sobre Mikroways"
  URL = "about"
  weight = 1

  [[Languages.es.menu.main]]
  parent = "La empresa"
  name = "El equipo"
  URL = "team"
  weight = 2

  [[Languages.es.menu.main]]
  parent = "La empresa"
  name = "Nuestros clientes"
  URL = "clients"
  weight = 3

[[Languages.es.menu.main]]
name = "Casos de éxito"
URL = "portfolio"
weight = 3

[[Languages.es.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.es.menu.main]]
name = "Contacto"
URL = "contact"
weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
white_logo = "images/logo-blanco.png"
home = "Home"
# Meta data
description = "En Mikroways somos especialistas en servicios de IT productivos y nuestra misión es construir puentes, usando la tecnología adecuada, que les permitan a nuestros clientes conquistar y materializar sus ideas."
author = "Mikroways"
# contact info
address = "9 #562 2A, La Plata, Buenos Aires, Argentina"
phone = "+54 (221) 447-3084"
email = "contacto@mikroways.net"
# copyright
copyright = "Copyright &copy; 2021 Mikroways &copy;"

# flickr photos
[[params.flickr_photos]]
image = "images/gallery/1.jpg"
[[params.flickr_photos]]
image = "images/gallery/2.jpg"
[[params.flickr_photos]]
image = "images/gallery/3.jpg"
[[params.flickr_photos]]
image = "images/gallery/4.jpg"
[[params.flickr_photos]]
image = "images/gallery/5.jpg"
[[params.flickr_photos]]
image = "images/gallery/6.jpg"
[[params.flickr_photos]]
image = "images/gallery/7.jpg"
[[params.flickr_photos]]
image = "images/gallery/8.jpg"
[[params.flickr_photos]]
image = "images/gallery/9.jpg"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-34.91179"
map_longitude = "-57.95820"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
name = "linkedin"
icon = "fa-linkedin" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/company/mikroways/"

[[params.social]]
name = "youtube"
icon = "fa-youtube"
link = "https://www.youtube.com/user/Mikroways"

[[params.social]]
name = "github"
icon = "fa-github" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://github.com/orgs/Mikroways/repositories"

[[params.social]]
name = "twitter"
icon = "fa-twitter" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/mikroways"

[[params.social]]
name = "instagram"
icon = "fa-instagram" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/mikroways/"

[[params.social]]
name = "facebook"
icon = "fa-facebook" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/Mikroways/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "We specialize in productive IT services, and our mission is to build bridges using the appropriate technology to help our clients conquer and materialize their ideas."
# copyright
copyright = "Copyright 2021 Mikroways"

################################### Spanish language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-ar"
contentDir = "content/spanish"
weight = 2
home = "Inicio"
# footer content
footer_content = "Somos especialistas en servicios de IT productivos y nuestra misión es construir puentes, usando la tecnología adecuada, que les permitan a nuestros clientes conquistar y materializar sus ideas."
copyright = "Copyright 2021 Mikroways"
